### ISSUE TITLE
train.py numpy np.hstack error

### ISSUE THREAD

**Issue by leodesigner** [ryokamoi/hybrid_textvae#1]
Hi,
I was playing with your code.
Got following error:
```
start training
epoch 1
Traceback (most recent call last):
  File "train.py", line 151, in <module>
    main()
  File "train.py", line 69, in main
    batchloader.next_batch(FLAGS.BATCH_SIZE, "train") 
  File "utils/batchloader.py", line 80, in next_batch
    return self.wrap_tensor(encoder_input)  
  File "utils/batchloader.py", line 99, in wrap_tensor
    decoder_input = np.array([np.hstack(([self.char_to_idx[self.go_token]], line[:len(line)-1])) for line in np.copy(input)])
  File "utils/batchloader.py", line 99, in <listcomp>
    decoder_input = np.array([np.hstack(([self.char_to_idx[self.go_token]], line[:len(line)-1])) for line in np.copy(input)]) 
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/shape_base.py", line 291, in hstack
    return _nx.concatenate(arrs, 0) 
ValueError: all the input arrays must have same number of dimensions
```
Did it run without issues for you ?
Thanks.

**Comment by leodesigner** [comment]
Fixed, had wrong data shape.
